name: P1B1
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy=4.0.1
  - keras-gpu=2.2.4
  - matplotlib=3.3.4
  - numba=0.53.1
  - numpy=1.19.2
  - patsy=0.5.1
  - pandas=1.1.3
  - python=3.6.13
  - requests=2.25.1
  - scikit-learn=0.24.1
  - statsmodels=0.11.0
  - tensorflow=1.15.0
  - tqdm=4.59.0
